# Generated by Django 5.0.6 on 2024-07-19 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="teacher_info",
            new_name="teachers",
        ),
    ]
