# Generated by Django 5.0.6 on 2024-07-12 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={"verbose_name": "Student"},
        ),
        migrations.AlterModelOptions(
            name="teacher",
            options={"verbose_name": "Teacher"},
        ),
    ]
