# Generated by Django 5.0.6 on 2024-07-23 07:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_alter_student_options_alter_teacher_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="teacher_info",
            new_name="teachers",
        ),
    ]
