# Generated by Django 5.0.6 on 2024-07-22 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_rename_teacher_info_student_teachers"),
    ]

    operations = [
        migrations.RenameField(
            model_name="teacher",
            old_name="user",
            new_name="teacher",
        ),
    ]
