# Generated by Django 5.0.6 on 2024-07-22 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_rename_user_student_student"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="student",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="teacher",
            old_name="teacher",
            new_name="user",
        ),
    ]
